spring:
  datasource:
    url: jdbc:postgresql://perfectly-prompt-egret.a1.pgedge.io:5432/tripbyday?sslmode=require
    username: app
    password: 6qrn9Oi48IbI2oQl48Be615v
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 837678669718-282ilen1gvbcq9moahd4hb4vpbtb1jjk.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 8082

