name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
            
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
            
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2</url>
                  </repository>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/AmbroseSu/TripByDayService</url>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                  <repository>
                    <id>github-repo</id>
                    <url>https://maven.pkg.github.com/AmbroseSu/TripByDayRepository</url>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                 </repositories>
              </profile>
            </profiles>
            <servers>
              <server>
                 <id>github</id>
                 <username>${{ github.actor }}</username>
                 <password>${{ secrets.JAVA_TOKEN }}</password>
               </server>
             </servers>
          </settings>' > ~/.m2/settings.xml
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
